"""Cognitia Reasoning Types.

Defines canonical reasoning modes, derivation steps, immutable reasoning traces,
reasoning input snapshots, candidate result structures, and explicit residuals.
All structures enforce deep immutability and snapshot safety.
"""

from __future__ import annotations

import enum
from dataclasses import dataclass, field
from typing import Any, Mapping, Sequence

from cognitia.abi.types import (
    CognitiveObject,
    Observation,
    SCHEMA_VERSION_V1,
    current_utc_timestamp,
    generate_entity_id,
)
from cognitia.epistemic.types import (
    Claim,
    EpistemicStatus,
    Evidence,
    EvidenceDirection,
    Hypothesis,
    Residual,
)
from cognitia.provenance.record import ProvenanceRecord, SourceType
from cognitia.rules.types import CognitiveRule


class ReasoningMode(str, enum.Enum):
    """Canonical reasoning modes supported by Cognitia."""

    DEDUCTION = "deduction"
    ABDUCTION = "abduction"
    ANALOGY = "analogy"
    COUNTERFACTUAL = "counterfactual"
    CAUSAL = "causal"


@dataclass(frozen=True)
class ReasoningStep:
    """An individual step in a deliberate reasoning derivation."""

    step_number: int
    inference_rule: str
    input_references: list[str] = field(default_factory=list)
    intermediate_claim: str = ""
    confidence: float = 1.0


@dataclass(frozen=True)
class ReasoningTrace(CognitiveObject):
    """Immutable audit trace recording a structured reasoning derivation.
    
    INVARIANTS:
    1. A reasoning trace is an immutable historical audit record.
    2. Reasoning output does not constitute physical truth, decision, or execution authority.
    3. Re-executing identical reasoning input against identical strategies produces identical traces.
    """

    mode: ReasoningMode = ReasoningMode.DEDUCTION
    premises: list[CognitiveObject] = field(default_factory=list)
    steps: list[ReasoningStep] = field(default_factory=list)
    conclusion: CognitiveObject = field(default_factory=CognitiveObject)
    confidence: float = 1.0
    provider: str = "deterministic_reasoner"
    provenance: ProvenanceRecord = field(
        default_factory=lambda: ProvenanceRecord(source_type=SourceType.REASONING_ENGINE)
    )


@dataclass(frozen=True)
class ReasoningResidual(CognitiveObject):
    """Explicitly recorded unknown, missing observation, or unmodeled factor."""

    factor_name: str = ""
    description: str = ""
    residual_type: str = "missing_observation"  # missing_observation, missing_rule, unmodeled_dynamic
    target_variable: str | None = None
    provenance: ProvenanceRecord = field(
        default_factory=lambda: ProvenanceRecord(source_type=SourceType.REASONING_ENGINE)
    )


@dataclass(frozen=True)
class DeductiveConclusion(CognitiveObject):
    """Outcome of a deterministic deductive derivation."""

    derived_attributes: tuple[tuple[str, Any], ...] = ()
    matched_rule_ids: tuple[str, ...] = ()
    satisfied_conditions: tuple[str, ...] = ()
    unsatisfied_conditions: tuple[str, ...] = ()
    residuals: tuple[ReasoningResidual, ...] = ()

    @property
    def derived_attributes_dict(self) -> dict[str, Any]:
        return dict(self.derived_attributes)


@dataclass(frozen=True)
class AbductiveHypotheses(CognitiveObject):
    """Candidate explanatory hypotheses generated by abductive inference."""

    candidate_hypotheses: tuple[Hypothesis, ...] = ()
    explanation_bases: tuple[tuple[str, str], ...] = ()  # (hypothesis_id, basis_description)
    unexplained_observations: tuple[str, ...] = ()
    residuals: tuple[ReasoningResidual, ...] = ()

    @property
    def explanation_bases_dict(self) -> dict[str, str]:
        return dict(self.explanation_bases)


@dataclass(frozen=True)
class AnalogicalMapping(CognitiveObject):
    """Structural analogy mapping between a source domain/pattern and target context."""

    source_structure_id: str = ""
    target_structure_id: str = ""
    correspondences: tuple[tuple[str, str], ...] = ()  # (source_element, target_element)
    structural_basis: str = ""
    similarity_score: float = 1.0
    known_limitations: tuple[str, ...] = ()
    is_equivalent: bool = False  # Always False unless explicit domain axiom states equivalence
    residuals: tuple[ReasoningResidual, ...] = ()

    @property
    def correspondences_dict(self) -> dict[str, str]:
        return dict(self.correspondences)


@dataclass(frozen=True)
class CausalHypothesis(CognitiveObject):
    """Explicit causal hypothesis relating cause and effect via a mechanism."""

    cause: str = ""
    effect: str = ""
    mechanism: str = ""
    supporting_evidence_ids: tuple[str, ...] = ()
    contradictory_evidence_ids: tuple[str, ...] = ()
    status: EpistemicStatus = EpistemicStatus.HYPOTHESIS
    assumptions: tuple[str, ...] = ()
    limitations: tuple[str, ...] = ()
    residuals: tuple[ReasoningResidual, ...] = ()


@dataclass(frozen=True)
class CounterfactualScenario(CognitiveObject):
    """Constrained hypothetical scenario computed under explicit intervention."""

    baseline_state: tuple[tuple[str, Any], ...] = ()
    intervention: tuple[tuple[str, Any], ...] = ()
    derived_state: tuple[tuple[str, Any], ...] = ()
    derivation_steps: tuple[str, ...] = ()
    is_observed: bool = False  # Invariant: Counterfactual != Observation
    is_hypothetical: bool = True
    assumptions: tuple[str, ...] = ()
    limitations: tuple[str, ...] = ()
    residuals: tuple[ReasoningResidual, ...] = ()

    @property
    def baseline_state_dict(self) -> dict[str, Any]:
        return dict(self.baseline_state)

    @property
    def intervention_dict(self) -> dict[str, Any]:
        return dict(self.intervention)

    @property
    def derived_state_dict(self) -> dict[str, Any]:
        return dict(self.derived_state)


@dataclass(frozen=True)
class ReasoningInput:
    """Immutable snapshot containing all data required for deterministic reasoning.
    
    INVARIANTS:
    1. Once constructed, ReasoningInput is deeply frozen.
    2. Reasoners MUST NEVER perform live lookups against mutable stores after snapshot creation.
    3. Contains exact references, premises, rules, and explicit configuration.
    """

    context_id: str = ""
    attention_result_id: str | None = None
    selected_item_ids: tuple[str, ...] = ()
    reasoning_mode: ReasoningMode = ReasoningMode.DEDUCTION
    premises: tuple[CognitiveObject, ...] = ()
    rules: tuple[CognitiveRule, ...] = ()
    constraints: tuple[tuple[str, Any], ...] = ()
    hypothetical_interventions: tuple[tuple[str, Any], ...] = ()
    causal_graph: tuple[tuple[str, str, str], ...] = ()  # (cause, effect, mechanism)
    analogy_source: tuple[tuple[str, Any], ...] = ()
    provenance: ProvenanceRecord = field(
        default_factory=lambda: ProvenanceRecord(source_type=SourceType.REASONING_ENGINE)
    )
    metadata: tuple[tuple[str, Any], ...] = ()

    def __init__(
        self,
        context_id: str = "",
        attention_result_id: str | None = None,
        selected_item_ids: Sequence[str] = (),
        reasoning_mode: ReasoningMode = ReasoningMode.DEDUCTION,
        premises: Sequence[CognitiveObject] = (),
        rules: Sequence[CognitiveRule] = (),
        constraints: Mapping[str, Any] | Sequence[tuple[str, Any]] | None = None,
        hypothetical_interventions: Mapping[str, Any] | Sequence[tuple[str, Any]] | None = None,
        causal_graph: Sequence[tuple[str, str, str]] = (),
        analogy_source: Mapping[str, Any] | Sequence[tuple[str, Any]] | None = None,
        provenance: ProvenanceRecord | None = None,
        metadata: Mapping[str, Any] | Sequence[tuple[str, Any]] | None = None,
    ) -> None:
        object.__setattr__(self, "context_id", str(context_id))
        object.__setattr__(self, "attention_result_id", str(attention_result_id) if attention_result_id else None)
        object.__setattr__(self, "selected_item_ids", tuple(selected_item_ids))
        object.__setattr__(self, "reasoning_mode", reasoning_mode if isinstance(reasoning_mode, ReasoningMode) else ReasoningMode(reasoning_mode))
        object.__setattr__(self, "premises", tuple(premises))
        object.__setattr__(self, "rules", tuple(rules))

        def _to_tuple_pairs(val: Any) -> tuple[tuple[str, Any], ...]:
            if val is None:
                return ()
            if isinstance(val, Mapping):
                return tuple(val.items())
            return tuple(val)

        object.__setattr__(self, "constraints", _to_tuple_pairs(constraints))
        object.__setattr__(self, "hypothetical_interventions", _to_tuple_pairs(hypothetical_interventions))
        object.__setattr__(self, "causal_graph", tuple(causal_graph))
        object.__setattr__(self, "analogy_source", _to_tuple_pairs(analogy_source))
        
        prov = provenance or ProvenanceRecord(
            source_type=SourceType.REASONING_ENGINE,
            producer_id="reasoning_snapshot_builder",
            parent_ids=[context_id] + ([attention_result_id] if attention_result_id else []) + [p.id for p in premises],
            is_deterministic=True,
        )
        object.__setattr__(self, "provenance", prov)
        object.__setattr__(self, "metadata", _to_tuple_pairs(metadata))

    @property
    def constraints_dict(self) -> dict[str, Any]:
        return dict(self.constraints)

    @property
    def hypothetical_interventions_dict(self) -> dict[str, Any]:
        return dict(self.hypothetical_interventions)

    @property
    def analogy_source_dict(self) -> dict[str, Any]:
        return dict(self.analogy_source)

    @property
    def metadata_dict(self) -> dict[str, Any]:
        return dict(self.metadata)


@dataclass(frozen=True)
class ReasoningResult(CognitiveObject):
    """Immutable composite container capturing all outputs of a reasoning execution.
    
    INVARIANTS:
    1. Contains candidate artifacts (hypotheses, claims, explanations, scenarios).
    2. Does NOT automatically register or mutate EpistemicService state.
    3. Preserves explicit residuals and contradictions.
    """

    reasoning_mode: ReasoningMode = ReasoningMode.DEDUCTION
    reasoning_input_id: str = ""
    candidate_conclusions: tuple[CognitiveObject, ...] = ()
    candidate_hypotheses: tuple[Hypothesis, ...] = ()
    candidate_claims: tuple[Claim, ...] = ()
    residuals: tuple[ReasoningResidual, ...] = ()
    contradictions_detected: tuple[str, ...] = ()
    derivation_metadata: tuple[tuple[str, Any], ...] = ()
    provenance: ProvenanceRecord = field(
        default_factory=lambda: ProvenanceRecord(source_type=SourceType.REASONING_ENGINE)
    )

    @property
    def derivation_metadata_dict(self) -> dict[str, Any]:
        return dict(self.derivation_metadata)
