"""Cognitia Canonical Cognitive ABI.

Defines the base type system, universal identifiers, timestamps,
and deterministic serialization contracts.
"""

from __future__ import annotations

import datetime
import decimal
import json
import uuid
from dataclasses import asdict, dataclass, field
from typing import Any, Final

SCHEMA_VERSION_V1: Final[str] = "1.0.0"


def generate_entity_id() -> str:
    """Generate a canonical UUIDv4 string."""
    return str(uuid.uuid4())


def current_utc_timestamp() -> str:
    """Return the current UTC timestamp formatted in ISO-8601 with microseconds."""
    return datetime.datetime.now(datetime.timezone.utc).isoformat()


class DeterministicSerializer:
    """Provides deterministic JSON serialization and hashing for Cognitive ABI objects."""

    @staticmethod
    def _default_encoder(obj: Any) -> Any:
        if isinstance(obj, (datetime.datetime, datetime.date)):
            return obj.isoformat()
        if isinstance(obj, uuid.UUID):
            return str(obj)
        if isinstance(obj, decimal.Decimal):
            return float(obj)
        if hasattr(obj, "to_dict"):
            return obj.to_dict()
        if hasattr(obj, "__dataclass_fields__"):
            return asdict(obj)
        if isinstance(obj, set):
            return sorted(list(obj))
        raise TypeError(f"Object of type {type(obj).__name__} is not JSON serializable")

    @classmethod
    def serialize(cls, data: Any) -> str:
        """Serialize data to a deterministic, canonical JSON string with sorted keys."""
        if hasattr(data, "__dataclass_fields__"):
            data_dict = asdict(data)
        elif hasattr(data, "to_dict"):
            data_dict = data.to_dict()
        else:
            data_dict = data

        return json.dumps(
            data_dict,
            default=cls._default_encoder,
            sort_keys=True,
            separators=(",", ":"),
            ensure_ascii=False,
        )

    @classmethod
    def deserialize(cls, json_str: str) -> dict[str, Any]:
        """Deserialize a canonical JSON string back into standard dictionary."""
        return json.loads(json_str)


@dataclass(frozen=True)
class CognitiveObject:
    """Base immutable cognitive entity carrying identity, schema version, and timestamp."""

    id: str = field(default_factory=generate_entity_id)
    schema_version: str = SCHEMA_VERSION_V1
    created_at: str = field(default_factory=current_utc_timestamp)
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    def serialize(self) -> str:
        return DeterministicSerializer.serialize(self)


@dataclass(frozen=True)
class Observation(CognitiveObject):
    """Raw or structured telemetry/input captured from a specific source."""

    source_id: str = "unknown"
    payload: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class Action(CognitiveObject):
    """Proposed or executed operational directive."""

    name: str = "unspecified"
    parameters: dict[str, Any] = field(default_factory=dict)
    target_node: str | None = None


@dataclass(frozen=True)
class Outcome(CognitiveObject):
    """Observed result or consequence of an action."""

    status: str = "success"
    metrics: dict[str, float] = field(default_factory=dict)
    resulting_observation: Observation | None = None


@dataclass(frozen=True)
class Decision(CognitiveObject):
    """Advisory cognitive recommendation generated by a capability."""

    proposal_type: str = "general_recommendation"
    proposed_action: Action = field(default_factory=Action)
    confidence: float = 1.0
    rationale: str | None = None
    provenance: Any | None = None

