"""Cognitia Adaptive Learning Layer (AL1, AL2 & AL3).

Decoupled machine learning provider subsystem providing typed-decision learning,
outcome-based learning, feedback loops, candidate models, evaluation, promotion proposals,
drift detection, deterministic replay, domain-scoped learning, knowledge isolation,
explicit advisory transfer proposals, real Laya provider integration boundary,
and complete model lifecycle governance with ZERO production authority.
"""

from cognitia.learning.contract import (
    AdaptiveInferenceRequest,
    AdaptiveLearningFailure,
    AdaptiveLearningProvider,
    AdaptiveLearningResult,
    CandidateStatus,
    DomainFreezeMode,
    DriftReport,
    DriftType,
    EvaluationMetric,
    FeedbackRecord,
    KnowledgeType,
    LearningCurvePoint,
    LearningDomain,
    LearningEvent,
    LearningTransferProposal,
    LearningUpdate,
    LifecycleEventType,
    ModelActivationObservation,
    ModelArtifactProvenance,
    ModelCandidate,
    ModelComparisonRecord,
    ModelComparisonReport,
    ModelEvaluation,
    ModelInputRepresentation,
    ModelLifecycleEvent,
    ModelLifecycleState,
    ModelPromotionDecision,
    ModelPromotionProposal,
    ModelRollbackDecision,
    ModelRollbackProposal,
    OutcomeRecord,
    PredictionRecord,
    PromotionDecisionRecord,
    RuntimeActivationState,
    TaskType,
    TransferCompatibilityResult,
    TransferCompatibilityStatus,
    TransferDecisionRecord,
    TransferType,
)
from cognitia.learning.drift import DriftDetector, StatisticalDriftDetector
from cognitia.learning.evaluation import ModelEvaluationEngine
from cognitia.learning.laya_provider import (
    LayaProvider,
    LayaProviderAdapter,
    LayaSurrogateProvider,
    RealLayaProvider,
)
from cognitia.learning.replay import LearningReplayEngine, ReplayVerificationResult
from cognitia.learning.representation import RepresentationAdapter
from cognitia.learning.service import AdaptiveLearningService
from cognitia.learning.transfer import LearningTransferEngine

__all__ = [
    "AdaptiveInferenceRequest",
    "AdaptiveLearningFailure",
    "AdaptiveLearningProvider",
    "AdaptiveLearningResult",
    "AdaptiveLearningService",
    "CandidateStatus",
    "DomainFreezeMode",
    "DriftDetector",
    "DriftReport",
    "DriftType",
    "EvaluationMetric",
    "FeedbackRecord",
    "KnowledgeType",
    "LayaProvider",
    "LayaProviderAdapter",
    "LayaSurrogateProvider",
    "LearningCurvePoint",
    "LearningDomain",
    "LearningEvent",
    "LearningReplayEngine",
    "LearningTransferEngine",
    "LearningTransferProposal",
    "LearningUpdate",
    "LifecycleEventType",
    "ModelActivationObservation",
    "ModelArtifactProvenance",
    "ModelCandidate",
    "ModelComparisonRecord",
    "ModelComparisonReport",
    "ModelEvaluation",
    "ModelEvaluationEngine",
    "ModelInputRepresentation",
    "ModelLifecycleEvent",
    "ModelLifecycleState",
    "ModelPromotionDecision",
    "ModelPromotionProposal",
    "ModelRollbackDecision",
    "ModelRollbackProposal",
    "OutcomeRecord",
    "PredictionRecord",
    "PromotionDecisionRecord",
    "RealLayaProvider",
    "ReplayVerificationResult",
    "RepresentationAdapter",
    "RuntimeActivationState",
    "StatisticalDriftDetector",
    "TaskType",
    "TransferCompatibilityResult",
    "TransferCompatibilityStatus",
    "TransferDecisionRecord",
    "TransferType",
]
